kind: pipeline
type: docker
name: armhf-raspbian-buster
platform:
  os: linux
  arch: arm
image_pull_secrets:
- dockerconfigjson
steps:
- name: fetch
  image: arm32v6/alpine:3.12
  commands:
  - apk add git
  - git fetch --tags 
  - git submodule update --init --recursive --remote 
- name: build
  image: plugins/docker
  environment:
    CLOUDSMITH_API_KEY:
      from_secret: CLOUDSMITH_API_KEY
  settings:
      repo: openhd/qopenhd
      dry_run: true
      username:
        from_secret: docker_openhd_username
      password:
        from_secret: docker_openhd_password
      dockerfile: Dockerfile-armhf-raspbian-buster
      build_args_from_env:
        - CLOUDSMITH_API_KEY
---

kind: pipeline
type: docker
name: armhf-raspbian-bullseye
platform:
  os: linux
  arch: arm
image_pull_secrets:
- dockerconfigjson
steps:
- name: fetch
  image: arm32v6/alpine:3.12
  commands:
  - apk add git
  - git fetch --tags 
  - git submodule update --init --recursive --remote 
- name: build
  image: plugins/docker
  environment:
    CLOUDSMITH_API_KEY:
      from_secret: CLOUDSMITH_API_KEY
  settings:
      repo: openhd/qopenhd
      dry_run: true
      username:
        from_secret: docker_openhd_username
      password:
        from_secret: docker_openhd_password
      dockerfile: Dockerfile-armhf-raspbian-bullseye
      build_args_from_env:
        - CLOUDSMITH_API_KEY
