FROM ghcr.io/openhd/bullseye-lite:v2.4

COPY .git /data/.git/

COPY . /data/

RUN apt-get update

WORKDIR /data

ARG CLOUDSMITH_API_KEY=000000000000

RUN export CLOUDSMITH_API_KEY=$CLOUDSMITH_API_KEY

RUN apt -y install build-essential


RUN /data/build.sh pi-bullseye
RUN /data/package.sh armhf raspbian bullseye docker
