name: Build Jetson ONLINE

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
 
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive   

      - name: Emulating Jetson
        id: push
        uses: pguyot/arm-runner-action@f204b58258d5b01e297eec6db036a14b11dc9ffa
        with:
          base_image: https://openhdfpv.org/wp-content/BaseImages/jetson-qemu.zip
          cpu: cortex-a53
          bootpartition:
          rootpartition: 1
          commands: |
            cat /etc/os-release
            uname -a
            sudo ./build.sh jetson-nano
            sudo ./package.sh jetson-nano bionic

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "qt"
          path: |
            *.deb
            *.log
          if-no-files-found: error
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
