name: Build RPI Legacy

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, ARM, legacy]
    timeout-minutes: 9000
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build qt
      run: |
       ls -a
       sudo apt update
       sudo bash install_dep.sh
       bash debug.sh
       sudo ./package.sh pi bullseye
       ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD-QT"
        path: |
          *.deb
          *.log
      
  
