name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: download older package
      run: |
       wget https://dl.cloudsmith.io/public/openhd/openhd-2-2-evo/deb/raspbian/pool/bullseye/main/o/op/openhd-qt-pi-bullseye-legacy_5.15.4-08070547/openhd-qt-pi-bullseye-legacy_5.15.4-08070547_armhf.deb
       sudo apt install binutils
       ar vx openhd-qt-pi-bullseye-legacy_5.15.4-08070547_armhf.deb
       rm openhd-qt-pi-bullseye-legacy_5.15.4-08070547_armhf.deb
       ls -a
       mkdir package
       cd package
       mv ../data.tar.xz ./data.tar.xz
       tar -xf data.tar.xz
       rm data.tar.xz
       ls -a
       sudo apt install ruby
       sudo gem install fpm
       echo $(pwd)
    - name: repackage
      run: |
       PACKAGE_NAME=openhd-qt
       PKGDIR=$(pwd)/package
       VERSION=5.15.4-$(date '+%m%d%H%M')-evo
       fpm -a armhf -s dir -t deb -n openhd-qt -v ${VERSION} -C ${PKGDIR} \
       $PLATFORM_CONFIGS \
        -p ${PACKAGE_NAME}_VERSION_ARCH.deb \
        --after-install after-install.sh \
        --provides openhd-qt \
        $PLATFORM_PACKAGES \
        -d "flite >= 2.0.0" \
        -d "flite1-dev >= 2.0.0" \
        -d "libasound2 >= 1.1.3" \
        -d "libdbus-1-3 >= 1.10.28" \
        -d "libdouble-conversion1" \
        -d "libdrm2 >= 2.4.74" \
        -d "libegl1-mesa >= 13.0.6" \
        -d "libfontconfig1 >= 2.11.0" \
        -d "libfreetype6 >= 2.6.3" \
        -d "libgbm1 >= 13.0.6" \
        -d "libgles2-mesa >= 13.0.6" \
        -d "libglib2.0-0 >= 2.50.3" \
        -d "libicu-dev >= 57.1" \
        -d "libinput-bin >= 1.6.3" \
        -d "libinput10 >= 1.6.3" \
        -d "libjpeg-dev > 0" \
        -d "libnss3" \
        -d "libpng16-16 >= 1.6.28" \
        -d "libpulse0 >= 10.0" \
        -d "libpulse-mainloop-glib0 >= 10.0" \
        -d "libspeechd-dev >= 0.8.6" \
        -d "libsqlite3-0 >= 3.16.2" \
        -d "libts-dev >= 1.0" \
        -d "libudev1 >= 0" \
        -d "mtdev-tools >= 0" \
        -d "pulseaudio >= 10.0" \
        -d "speech-dispatcher-flite >= 0.8.6" \
        -d "libxcb-xfixes0 >= 1.12" \
        -d "libxkbcommon0 >= 0.7.1" || exit 1 
       
    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD-QT"
        path: |
          *.deb
          *.log
        if-no-files-found: error

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-3-evo"
        distro: "raspbian"
        release: "bullseye"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"
        
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
