name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, ARM]
    steps:
      - name: test
        run: |
          echo "DT=$(date +'%Y-%m-%d_%H%M')" >> $GITHUB_ENV
          echo "BRANCH=${GITHUB_REF##*/}" >> $GITHUB_ENV    

      - name: Clean UP
        run: |
          sudo rm -Rf *

      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive
    
      - name: Build with make
        run: |
          sudo ./build.sh armhf raspbian bullseye
          sudo ./package.sh armhf raspbian bullseye

      - name: Upload to Github
        uses: 'actions/upload-artifact@v2'
        with:
          name: "Open.HD"
          path: |
            *.deb
            *.log
          if-no-files-found: error
          
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
