name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: build qt
      run: |
       wget https://dl.cloudsmith.io/public/openhd/openhd-2-2-evo/deb/raspbian/pool/bullseye/main/o/op/openhd-qt-pi-bullseye-legacy_5.15.4-08070547/openhd-qt-pi-bullseye-legacy_5.15.4-08070547_armhf.deb
       sudo apt install binutils
       ar vx openhd-qt-pi-bullseye-legacy_5.15.4-08070547_armhf.deb
       ls -a
       tar -xf data.tar.xz
       ls -a




    # - name: Upload to Github
    #   uses: 'actions/upload-artifact@v2'
    #   with:
    #     name: "Open.HD-QT"
    #     path: |
    #       *.deb
    #       *.log
    #     if-no-files-found: error

    # - name: Push
    #   id: push
    #   uses: cloudsmith-io/action@master
    #   with:
    #     api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
    #     command: "push"
    #     format: "deb"
    #     owner: "openhd"
    #     repo: "openhd-2-2-3-evo"
    #     distro: "raspbian"
    #     release: "bullseye"
    #     republish: "true" # needed ONLY if version is not changing
    #     file: "*.deb"
        
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
