name: Build RPI

on: [push]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: [self-hosted, linux, ARM]
    timeout-minutes: 900
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build qt
      run: |
       ls -a
       sudo apt update
       bash debug.sh
       sudo ./package.sh armhf raspbian bullseye
       ls -a

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD"
        path: |
          qt-raspberrypi/*.deb
          qt-raspberrypi/*.log

        
      #- name: Install
      #  run: |
      #    cd OpenHD/build
      #    sudo cmake --install .
      #- name: Build ninja
      #  run: |
      #    sudo apt -y install ninja-build
      #    cd OpenHD
      #    ./build_cmake.sh
