name: Build X86 Jammy

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build qt
      run: |
       ls -a
       sudo apt update
       chmod +x install_dep.sh
       sudo apt install -y libdrm-dev libdrm-amdgpu1 libdrm-nouveau2 libdrm-radeon1
       sudo ./install_dep.sh
       bash ./build.sh x86-jammy
       sudo ./package.sh x86 jammy
       ls -a
       ls -a /tmp

    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD-QT"
        path: |
          *.deb
          *.log

    - name: Push
      id: push
      uses: cloudsmith-io/action@master
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: "push"
        format: "deb"
        owner: "openhd"
        repo: "openhd-2-2-evo"
        distro: "ubuntu"
        release: "jammy"
        republish: "true" # needed ONLY if version is not changing
        file: "*.deb"        
  
