name: Build X86 Jammy

on: [push]

env:
  BUILD_TYPE: Release

jobs:
  build:

    runs-on: ubuntu-22.04
    env:
      CLOUDSMITH_API_KEY: ${{ secrets.CLOUDSMITH_API_KEY }}
    steps:
    - name: build qt
      run: |
       echo "hello world"
       wget https://dl.cloudsmith.io/public/openhd/openhd-2-3-evo/deb/ubuntu/pool/jammy/main/o/op/openhd-qt-x86-jammy_5.15.7-01152350/openhd-qt-x86-jammy_5.15.7-01152350_amd64.deb
       ls -a
       mkdir -p newpack oldpack/DEBIAN
       dpkg-deb -x *.deb oldpack/
       cd oldpack/DEBIAN
       ls
       rm control
       wget https://geekymind.de/control
       cd ..
       dpkg-deb -Z xz -b oldpack/ newpack/
       cd newpack
       ls
       cp * ../
       
    - name: Upload to Github
      uses: 'actions/upload-artifact@v2'
      with:
        name: "Open.HD-QT"
        path: |
          *.deb
          *.log

    # - name: Push
    #   id: push
    #   uses: cloudsmith-io/action@master
    #   with:
    #     api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
    #     command: "push"
    #     format: "deb"
    #     owner: "openhd"
    #     repo: "openhd-2-3-evo"
    #     distro: "ubuntu"
    #     release: "jammy"
    #     republish: "true" # needed ONLY if version is not changing
    #     file: "*.deb"        
  
